---
- hosts: ceph-mons
  become: true
  roles:
    - ceph.ceph-mon
  serial: 1
- hosts: osd-loopback
  become: true
  roles:
    - osd-loopback
- hosts: ceph-osds
  become: true
  roles:
    - ceph.ceph-osd
- hosts: ceph-mdss
  become: true
  roles:
    - ceph.ceph-mds
- hosts: ceph-rgws
  become: true
  roles:
    - ceph.ceph-rgw
  tasks:
    - name: create radosgw user ({{ radosgw_user }})
      become: true
      command: radosgw-admin user create --uid={{ radosgw_user }} --display-name={{ radosgw_user }}
...
