---
- name: create folder for ipyparallel files
  become: yes
  file:
    path: "/nfs/ipyparallel/profile_{{ ipyparallel_profile | default('default')}}"
    state: directory
    mode: 0777
- name: start ipyparallel controller
  become: yes
  become_method: sudo
  # docker_service module does not currently work with Docker >=1.13
  # swarm-mode
  command: "docker service create --network cluster-overlay --mount type=bind,source=/nfs/ipyparallel/profile_{{ ipyparallel_profile | default('default') }},destination=/home/jovyan/.ipython/profile_default --name ipcontroller bmenn/datascience-notebook ipcontroller --ip=* --location=ipcontroller"
...
