---
- name: update certificates
  become: yes
  apt:
    name:
      - apt-transport-https
      - ca-certificates
    update_cache: yes
    state: present
- name: add docker repo key
  become: yes
  apt_key:
    keyserver: hkp://p80.pool.sks-keyservers.net:80
    id: 58118E89F3A912897C070ADBF76221572C52609D
    state: present
- name: add docker repo
  become: yes
  apt_repository:
    repo: "deb https://apt.dockerproject.org/repo ubuntu-trusty main"
    state: present
- name: install docker
  become: yes
  apt:
    name: docker-engine
    update_cache: yes
    state: present
- name: install docker-py
  become: yes
  pip:
    name: docker-py
    state: present
  notify:
    - start docker
...
