---
- name: update certificates
  become: yes
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
    update_cache: yes
    state: present
- name: add docker repo key
  become: yes
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
- name: get distro name
  command: lsb_release -cs
  register: distro_name
- name: add docker repo
  become: yes
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ distro_name.stdout }} stable"
    state: present
- name: install docker
  become: yes
  apt:
    name: docker-ce
    update_cache: yes
    state: present
- name: install docker-py
  become: yes
  pip:
    name: docker
    state: present
  notify:
    - start docker
- name: install pyyaml
  become: yes
  pip:
    name: pyyaml
    state: present
- name: install python docker-compose
  become: yes
  pip:
    name: docker-compose
    state: present
...
