---
- name: start jupyter notebook
  become: yes
  become_method: sudo
  docker_service:
    project_name: notebook
    definition:
      version: '2'
      services:
        jupyter:
          image: jupyter/datascience-notebook
          ports:
            - 8888:8888
  register: output
- name: check notebook service is running
  assert:
    that:
      - "jupyter.notebook_jupyter_1.state.running"
...
