---
- name: start jupyter notebook
  become: yes
  become_method: sudo
  # docker_service module does not currently work with Docker >=1.13
  # swarm-mode
  command: "docker service create --network cluster-overlay -p 8888:8888 --mount type=bind,source=/nfs,destination=/nfs --mount type=bind,source=/nfs/ipyparallel/profile_{{ ipyparallel_profile | default('default') }},destination=/home/jovyan/.ipython/profile_default --name jupyter-notebook bmenn/datascience-notebook start-notebook.sh --NotebookApp.notebook_dir=/nfs"
...
