---
- name: get advertise ip
  shell: " ip addr show dev enp0s8 | grep \"inet\\b\" | awk '{ print $2 }' | cut -f 1 -d '/'"
  register: advertise_ip
- name: initialize swarm cluster
  become: yes
  become_method: sudo
  command: "docker swarm init --advertise-addr {{ advertise_ip.stdout }}"
- name: create cluster overlay network
  become: yes
  become_method: sudo
  command: "docker network create --driver overlay cluster-overlay"
...
